config/routes.rb
Rails.application.routes.draw do

  resources :books do
    resources :notes, only: [:create, :destroy]#specify which restful actions you need
  end
  root to: "books#index"

  resources :sessions, only: [:new, :create, :destroy]

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :reviewer
  has_many :notes, dependent: :destroy
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :book
end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
	
	has_secure_password

	has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_login
  helper_method :logged_in?, :current_user

  protected
  def ensure_login
  	# Always go to login page unless session contains reviewer_id
  	redirect_to login_path unless session[:reviewer_id]
  end

  def logged_in?
  	session[:reviewer_id] # nil is false
  end

  def current_user
  	@current_user ||= Reviewer.find(session[:reviewer_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = current_user.books.paginate(page: params[:page], per_page: 10)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = current_user.books.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :set_book, only: [:create, :destroy]

	def create
		@note = @book.notes.new(note_params)
		if @note.save
			redirect_to @book, notice: "Note successfully added!"
		else
			redirect_to @book, alert: "Unable to add note!"
		end
	end

	def destroy
		@note = @book.notes.find(params[:id])
		@note.destroy
		redirect_to @book, notice: "Note deleted!"
	end

	private
	def set_book
		@book = Book.find(params[:book_id])
	end

	def note_params
		params.require(:note).permit(:title, :note)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_login, only: [:new, :create]
  def new
  	# Login Page - new.html.erb
  end

  def create
  	reviewer = Reviewer.find_by(name: params[:reviewer][:name])
  	password = params[:reviewer][:password]

  	if reviewer && reviewer.authenticate(password)
  		session[:reviewer_id] = reviewer.id
  		redirect_to root_path, notice: "Logged in successfully"
  	else
  		redirect_to login_path, alert: "Invalid username/password combination"
  	end
  end

  def destroy
  	reset_session #wipe out session and everything in it
  	redirect_to login_path, notice: "You have been logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p/>

<%= will_paginate @books %>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="book">
	<%= content_tag :span, "#{@book.name} (#{@book.author})", class: "book-title" %>
	<%= link_to 'Edit', edit_book_path(@book) %>
</div>

<div id="notes">
	<%= render @book.notes %>
</div>

<div>
	<%= form_for([@book, @book.notes.new]) do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :note %>
		<%= f.text_area :note, size: "25x5" %>
	</div>
	<div class="actions">
		<%= f.submit "Add New Note" %>
	</div>
	<% end %>
</div>

<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IReviewed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
	<div style='float: right;'>
		Logged in as <%= current_user.name %> |
		<%= link_to "Logout", logout_path, method: :delete %>
	</div>
<% end %>

<% flash.each do |key, value| %>
	<p id= '<%= key %>'><%= value %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<div class="note">
  <div>
    <%= content_tag :span, "#{note.title} (#{time_ago_in_words note.created_at} ago)", 
      class: "note-title" %>
    <%= link_to "Delete Note", [@book, note], method: :delete %>
  </div>
  <div><%= simple_format note.note %></div>
</div>